### ISSUE TITLE
Document improvements to telnet support

### ISSUE THREAD

**Issue by srorso** [hercules-390/html#1] opened 2016-04-29 23:58 UTC
Commits from Hyperion issue [#100](https://github.com/hercules-390/hyperion/issues/100) have greatly improved telnet support provided by Hyperion.  Document those improvements, including specific configuration requirements for telnet clients where known (PuTTY in particular).

**Comment by srorso** [comment] 2016-04-30 13:18
A preliminary view of the Telnet/tn3270 page may be [viewed here](http://srorso.github.io/html/telnet.html).  

I will add sections for Windows 10 and NT telnets and x3270 tn3270 once I have some feedback.  I will be happy to include other telnet/tn3270 applications; just send me screen shots and a brief note about application-essential settings.  

Re feedback: comments on everything welcomed: content, layout, style, font selection, whatever.  

Some notes/questions:  
1) To Enrico/John/S390guy: Could one of you confirm that updates to issues in this repository are e-mailed to Hercules developers?
2) I have exported the screenshots as .png because that gave the best result.  Is there any site standard that would limit images to gif?
3) I've avoided pop-ups for the screen shots, but I believe that popups would provide a better look and feel.  Comments?
4) HTML coding was done in Visual Studio 2015.  Once the repository is cloned, open an html page with "Open with...," select HTML (Web Forms) Editor, and click Set as Default. The Design and Source views are pretty handy.  
5) I haven't included the Hercules style sheet yet but I will.  I'll need it for the Windows Telnet applications.

**Comment by jphartmann** [comment] 2016-04-30 13:40
Confirmed.

**Comment by Fish-Git** [comment] 2016-04-30 16:44
> 2) ... Is there any site standard that would limit images to gif?

Not that I'm aware of. PNG is fine and in fact preferred IMO since you can set transparency.

> 3) I've avoided pop-ups for the screen shots, but I believe that popups would provide a better look and feel. Comments?

Others may feel differently but I think pop-ups would be nice.

All in all it looks pretty good to me. If I were to nitpick anything it would be the table of PuTTY options: I'd personally prefer to use a single line border (the double-line border is ugly IMO). A few pixels of additional horizontal and vertical space within each cell might be nice too.

May I presume that we'll eventually have some content for x3270 and c3270 too?

Good job, Steve!

**Comment by ivan-w** [comment] 2016-04-30 16:54
Le 30/04/2016 à 18:44, Fish-Git a écrit :

> ```
> 2) ... Is there any site standard that would limit images to gif?
> ```
> 
> Not that I'm aware of. PNG is fine and in fact preferred IMO since you 
> can set transparency.
> 
> GIF also has some support for transparency (not a true alpha channel 
> though) but allows an index in the palette to be declared transparent.

--Ivan

**Comment by srorso** [comment] 2016-04-30 17:30
> On Apr 30, 2016, at 12:44 PM, Fish-Git notifications@github.com wrote:
> 
> 3) I've avoided pop-ups for the screen shots, but I believe that popups would provide a better look and feel. Comments?
> 
> Others may feel differently but I think pop-ups would be nice.

I agree; other opinions, anyone?

> I'd personally prefer to use a single line border (the double-line border is ugly IMO). A few pixels of additional horizontal and vertical space within each cell might be nice too.
> 
> This is exactly the feedback I seek; thanks.  More is welcomed. 
> May I presume that we'll eventually have some content for x3270 and c3270 too?
> 
> x3270: yes; it's what I use. 

c3270: I don't have that and I'm not sure it's free. 

Best regards,
Steve Orso

+1 610 217 7050

**Comment by Fish-Git** [comment] 2016-04-30 18:14
Um ... as far as I know, [x3270 and c3270](http://x3270.bgp.nu/) are the same product. &nbsp; `:)`

**Comment by ivan-w** [comment] 2016-04-30 18:18
Le 30/04/2016 à 20:14, Fish-Git a écrit :

> Um ... as far as I know, x3270 and c3270 http://x3270.bgp.nu/ are 
> the same product. |:)|
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub 
> https://github.com/hercules-390/html/issues/1#issuecomment-215984740
> 
> They are part of the same project.

But c3270 is a Curses/ncurses version while x3270 is the X11 version.

I now use Tom Brenann's 3270 emulator.

--Ivan

**Comment by srorso** [comment] 2016-05-01 15:11
Further updates incorporating some suggestions and adding documentation for wc3270, the native windows variant of x3270/c3270.  See it [here](http://srorso.github.io/html/telnet.html), not that it has moved.

Feedback / critique welcomed.  

I'll install x3270/c3270 on my virtual Debian to get some experience with that, enough to document anyway.  If someone will post Vista tn32720 configuration screen shots, I'll document and include.  I don't want to install the trial version unless absolutely necessary.  My laptop has enough nonsense on it.  :-)  

Fish wrote earlier:

> Um ... as far as I know, x3270 and c3270 are the same product.   :)

Touché.  And I don't use x3270 anyway.  I use the native windows app wc3270.

**Comment by Fish-Git** [comment] 2016-05-01 18:51
Typos: wc3270 section, review changes box:
- devicce s/b device
- If a groupname is provide, s/b If a groupname is provided,

I did not bother proof-reading the entire web page to see if there were any others. Those were the only two that jumped out at me so I thought I'd mention them.

Just a reminder too: when you're satisfied with your changes, commit them to Hyperion first, and then copy your changes over to your Hyperion-HTML clone and commit them there too. (And of course push your changes after you commit them, but I'm pretty sure you already know that.)

Looking good, Steve! &nbsp; `:)`

**Comment by Fish-Git** [comment] 2016-05-01 18:57
p.s. While I'm doubting there's really any need to explain how to use Tom Brennan's Vista TN3270 product (unless you yourself see a need or you're really overly enthusiastic) it wouldn't hurt to at least make your existing mention of his product at the top of the page into a hyperlink.

And even though the link should probably be to his product's main web page (http://www.tombrennansoftware.com/index.html), I personally think a link to one of his screen shots (such as http://www.tombrennansoftware.com/edit.html) would be better.

Others of course may feel differently.

**Comment by Fish-Git** [comment] 2016-05-01 19:03
Should we have links to as many other TN3270 emulators we can find too? Or would that be overkill?

I'm only asking since if we provide links to some but not others then accusations of favoritism could be levied against us (not that I'm all that worried about such issues).

Comments anyone?

**Comment by srorso** [comment] 2016-05-01 21:41
Fish wrote:

> ... commit them to Hyperion first, and then copy your changes over to your Hyperion-HTML

Thanks!! I would have missed that.  

> Typos: wc3270 section, review changes box:

Corrected.  Many thanks.  I  see there's a spellcheck extension for VS2015; I'll have to try that.   Till then, ugh, proofreading.  

> Should we have links to as many other TN3270 emulators ....  accusations of favoritism could be levied 

My first thought in writing the page is to give the newbie a shot at setting things up without calling for help.  So including (mostly) free solutions that are known to work fit that.  I've revised wording to deal with the favoritism issue.  

I care, but not that much, about this because favoritism rants just waste time.  And if there is a better solution, I'd like to know, so I'll invite sharing with the Hercules-390 user group.  If there's interest, we can add a more comprehensive list at the end...but I think there are plenty of "best app for..." lists out there.  

One lack that I lack the hardware to address: Mac (I lack a Mac).  The next time I'm in Everett I'll bug my brother, who uses Mac.  I'm sure the telnet is fine and setting local echo is easy.  But what tn3270 solutions are in use?  I found a [free one](https://www.brown.edu/cis/tn3270/) from Brown University, but I can't test.  

I believe that we have a mac user or two in the developers group.

**Comment by ghost** [comment] 2016-05-01 21:48
as far as I know , I am the only one ( using a MAC )

NEVER  had any problems with apple telnet 
the Brown University tn3270 works, but the configuration is not friendly
especially for the keyboard side

I am using ZOC… which works  on apple and on windows 
it is pretty generic telnet client with lots of options 

it works like a charm
cheers
enrico

**Comment by srorso** [comment] 2016-05-03 13:17
"Final" draft at [Telnet How-to](http://srorso.github.io/html/telnet.html).  Leaner and cleaner.  

Many thanks to all who provided feedback.  If you have more, I'll be glad to have it.

**Comment by Fish-Git** [comment] 2016-05-03 17:55
I'm not in charge here (no one is really, but I like to think of Harold as our leader) but I say go ahead and commit it.  It looks great to me.

Remember: [Hyperion repository](https://github.com/hercules-390/hyperion) first, then the [html repository](https://github.com/hercules-390/html)! &nbsp;(*)

(*)&nbsp; Or vice versa of course.  The only important thing to remember is that updates to our html documentation needs to be made in _both_ places.  They need to be committed to our main [Hyperion repository](https://github.com/hercules-390/hyperion) since the html documentation comes with the Hyperion package/product itself, and they need to also be made to our separate [html repository](https://github.com/hercules-390/html) too so the changes can be visible to people on the web.

**Comment by Fish-Git** [comment] 2016-05-03 17:58
p.s. Don't forget to add the images too! &nbsp; `:)`

**Comment by srorso** [comment] 2016-05-03 18:04
The images are in the commit with the page. I still have to mess with links on the config page.   

Git --cherrypick should make the duplication easy. 

Best regards,
Steve Orso

+1 610 217 7050

**Comment by dasdman** [comment] 2016-05-03 19:23
On 05/03/2016 06:17 AM, srorso wrote:

> "Final" draft at Telnet How-to 
> http://srorso.github.io/html/telnet.html. Leaner and cleaner.
> 
> Many thanks to all who provided feedback. If you have more, I'll be 
> glad to have it.
> 
> Looking good, but "Windows 10 telnet", I believe, should be Windows XP 
> and newer. I know I've been using the telnet command directly under 
> Windows since XP (although it did have to be selected for installation).

Mark

**Comment by dasdman** [comment] 2016-05-03 19:48
Under "Windows 10 telnet," there is a typographical error:

```
Unlike PuTTY, is is difficult...
```

Need to change "is is" to "it is".

**Comment by srorso** [comment] 2016-05-03 20:33
Hi Mark:

> Need to change "is is" to "it is".

Thanks; will do.  I appreciate the careful reading.  

> "Windows 10 telnet", I believe, should be Windows XP and newer. 

I believe that Telnet from WinXP through 10 on the workstation--and the corresponding server versions--are all the same beast and will work as well.  But I don't know that for certain, so I am reluctant to say that they work too.  I will include--as my supposition--the thought that WinXP and better telnets all work the same, and I can note those that I receive reports of "working."  

Not that I expect to receive many reports.  Win Telnet isn't very good and didn't work at all until Fish did his magic.

Best Regards,
Steve Orso

**Closed as completed** 2016-05-06 13:53 UTC
Labels: enhancement
